name: Power Alerts CI/CD Pipeline

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

env:
  AWS_REGION: us-east-1

jobs:
  test:
    name: Run Tests & Security Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest boto3 pymongo requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run security scan
      run: |
        echo "🔍 Scanning for hardcoded AWS credentials..."
        if grep -r "AKIA[0-9A-Z]{16}\|sk-[a-zA-Z0-9]{40}" \
          --include="*.py" --include="*.json" --include="*.yaml" --include="*.yml" \
          --exclude-dir=".git" --exclude-dir="__pycache__" --exclude-dir=".aws-sam" \
          --exclude-dir="urllib3" --exclude-dir="pymongo" --exclude-dir="requests" \
          --exclude-dir="dateutil" --exclude-dir="dns" --exclude-dir=".history" \
          lambda_function.py template.yaml *.py 2>/dev/null || true; then
          echo "❌ AWS credentials found in source code!"
          exit 1
        fi
        echo "✅ Security scan passed"
    
    - name: Run unit tests
      run: |
        python -m pytest tests/ -v || echo "No tests found, continuing..."
        
        # Syntax check
        python -c "import lambda_function; print('✅ Lambda function syntax OK')"
        
        # Import test
        python -c "
        try:
            from lambda_function import get_report_period
            print('✅ Function imports OK')
        except ImportError as e:
            print(f'❌ Import error: {e}')
            exit(1)
        "

  deploy-dev:
    name: Deploy to Development
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    environment: development
    
    outputs:
      dev-deployment-status: ${{ steps.dev-deploy.outcome }}
      dev-test-status: ${{ steps.dev-test.outcome }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Set up SAM CLI
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Build SAM application
      run: sam build
    
    - name: Deploy to Development
      id: dev-deploy
      run: |
        sam deploy \
          --stack-name power-alerts-dev \
          --parameter-overrides Stage=dev \
          --capabilities CAPABILITY_IAM \
          --resolve-s3 \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
    
    - name: Test Development Deployment
      id: dev-test
      run: |
        echo "🧪 Testing development deployment..."
        aws lambda invoke \
          --function-name power-transaction-monitor-dev \
          --payload '{"test": true, "source": "github-actions-dev"}' \
          --cli-binary-format raw-in-base64-out \
          test-output.json
        
        echo "📄 Dev test response:"
        cat test-output.json
        
        # Validate response
        if grep -q "successfully\|message" test-output.json; then
          echo "✅ Development deployment test PASSED"
        else
          echo "❌ Development deployment test FAILED"
          exit 1
        fi
    
    - name: Notify Slack (Dev Success)
      if: success()
      run: |
        curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"✅ Power Alerts DEV deployment successful! Ready for production.\", \"attachments\":[{\"color\":\"good\",\"fields\":[{\"title\":\"Branch\",\"value\":\"develop\",\"short\":true},{\"title\":\"Next\",\"value\":\"Auto-promoting to production...\",\"short\":true}]}]}" \
          ${{ secrets.SLACK_WEBHOOK_URL }} || echo "Slack notification failed"
    
    - name: Notify Slack (Dev Failed)
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"❌ Power Alerts DEV deployment FAILED!\", \"attachments\":[{\"color\":\"danger\",\"fields\":[{\"title\":\"Branch\",\"value\":\"develop\",\"short\":true},{\"title\":\"Action\",\"value\":\"Check logs and fix issues\",\"short\":true}]}]}" \
          ${{ secrets.SLACK_WEBHOOK_URL }} || echo "Slack notification failed"

  promote-to-prod:
    name: Auto-Promote to Production
    needs: deploy-dev
    runs-on: ubuntu-latest
    if: needs.deploy-dev.outputs.dev-deployment-status == 'success' && needs.deploy-dev.outputs.dev-test-status == 'success'
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Set up SAM CLI
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Build SAM application
      run: sam build
    
    - name: Deploy to Production
      id: prod-deploy
      run: |
        echo "🚀 Auto-promoting to production..."
        sam deploy \
          --stack-name power-alerts-prod \
          --parameter-overrides Stage=prod \
          --capabilities CAPABILITY_IAM \
          --resolve-s3 \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
    
    - name: Test Production Deployment
      id: prod-test
      run: |
        echo "🧪 Testing production deployment..."
        aws lambda invoke \
          --function-name power-transaction-monitor-prod \
          --payload '{"test": true, "source": "github-actions-prod"}' \
          --cli-binary-format raw-in-base64-out \
          test-output.json
        
        echo "📄 Prod test response:"
        cat test-output.json
        
        # Validate response
        if grep -q "successfully\|message" test-output.json; then
          echo "✅ Production deployment test PASSED"
        else
          echo "❌ Production deployment test FAILED"
          exit 1
        fi
    
    - name: Notify Slack (Production Success)
      if: success()
      run: |
        curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"🚀 Power Alerts PRODUCTION deployment successful!\", \"attachments\":[{\"color\":\"good\",\"fields\":[{\"title\":\"Promoted From\",\"value\":\"develop branch\",\"short\":true},{\"title\":\"Status\",\"value\":\"Live in production ✨\",\"short\":true},{\"title\":\"Commit\",\"value\":\"${{ github.sha }}\",\"short\":false}]}]}" \
          ${{ secrets.SLACK_WEBHOOK_URL }} || echo "Slack notification failed"
    
    - name: Notify Slack (Production Failed)
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"🚨 Power Alerts PRODUCTION deployment FAILED!\", \"attachments\":[{\"color\":\"danger\",\"fields\":[{\"title\":\"Issue\",\"value\":\"Production deployment failed after successful dev deployment\",\"short\":false},{\"title\":\"Action Required\",\"value\":\"Immediate investigation needed\",\"short\":true}]}]}" \
          ${{ secrets.SLACK_WEBHOOK_URL }} || echo "Slack notification failed"

  manual-prod-deploy:
    name: Manual Production Deploy (main branch)
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Set up SAM CLI
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Build SAM application
      run: sam build
    
    - name: Deploy to Production (Manual)
      run: |
        echo "🔧 Manual production deployment from main branch..."
        sam deploy \
          --stack-name power-alerts-prod \
          --parameter-overrides Stage=prod \
          --capabilities CAPABILITY_IAM \
          --resolve-s3 \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
    
    - name: Test Production Deployment
      run: |
        echo "🧪 Testing production deployment..."
        aws lambda invoke \
          --function-name power-transaction-monitor-prod \
          --payload '{"test": true, "source": "github-actions-manual"}' \
          --cli-binary-format raw-in-base64-out \
          test-output.json
        
        cat test-output.json
    
    - name: Notify Slack (Manual Deploy)
      if: always()
      run: |
        STATUS="${{ job.status }}"
        if [ "$STATUS" = "success" ]; then
          EMOJI="🔧"
          COLOR="warning"
          MESSAGE="Power Alerts PRODUCTION manually deployed from main branch"
        else
          EMOJI="🚨"
          COLOR="danger"
          MESSAGE="Manual PRODUCTION deployment from main branch FAILED!"
        fi
        
        curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"$EMOJI $MESSAGE\", \"attachments\":[{\"color\":\"$COLOR\",\"fields\":[{\"title\":\"Branch\",\"value\":\"main (manual)\",\"short\":true},{\"title\":\"Type\",\"value\":\"Direct deployment\",\"short\":true}]}]}" \
          ${{ secrets.SLACK_WEBHOOK_URL }} || echo "Slack notification failed"